### ISSUE TITLE
Problem with Babel6

### ISSUE THREAD

**Issue by OracPrime** [romainberger/react-portal-tooltip#10]
Hi!

Your .babelrc is incompatible with Babel6 (I think).  Certainly with the setup I'm using I'm getting 

Module build failed: ReferenceError: [BABEL] <path>\node_modules\react-portal-tooltip\lib\index.js: Using removed Babel 5 option: <path>\node_modules\react-portal-tooltip\.babelrc.stage

I suspect that (from other discussions) "...you need to add .babel.rc to the npmignore"  (whatever that means, I'm a bit of a noob at this!)

**Comment by romainberger** [comment]
Hi!

Good catch thanks! That's exactly it, I'm using babel 5 in this module (I could update but I haven't yet), and this can provoke an error in babel 6 projects. I've fixed this in version [1.0.5](https://github.com/romainberger/react-portal-tooltip/releases/tag/v1.0.5).

To explain quickly, the `.npmignore` is a file pretty much similar to a `.gitignore` but that defines files (or directories) that won't be published to npm. So adding `.babelrc` to it will prevent the file to be included in the module and to break in other projects. I hope I'm clear :)

Thanks again
