### ISSUE TITLE
What's the correct way on using Link from react-router inside a tooltip?

### ISSUE THREAD

**Issue by mnazim** [romainberger/react-portal-tooltip#15]
Hello If I use `Link` component from `react-router` inside tooltip I get
``` 
Link.js:95 Uncaught TypeError: Cannot read property 'pushState' of undefined
```

I am us Tooltip like this

```
<div className="collageImage" style={{ width: this.props.size + 'px', height: this.props.size + 'px'}} >
  <img id={elID}
       onMouseEnter={::this.showTooltip}
       onMouseLeave={::this.hideTooltip}
       className=""
       src={record.image_collage}
       style={{ width: this.props.size + 'px', height: this.props.size + 'px'}} />
  <ToolTip pushState={this.props.pushState} active={this.state.isTooltipActive}
           position="bottom"
           arrow="center"
           parent={'#'+elID}
           tooltipTimeout="3000">
    <div className="collageImagePopover">
      <div className="collageImagePopoverTitle">{record.name}</div>
      <div className="collageImagePopoverText">{record.text}</div>
      <Link pushState={this.props.pushState} to={'/record/' + record.id} className="collageImagePopoverLink"> Read More </Link>
    </div>
  </ToolTip>
</div>
```

Another question I have is, that how do I add css for customising the position of popover. I want to move it up 10px from where it's displayed right now.

Thanks.

**Comment by romainberger** [comment]
Hi,

Can you tell me which version of react-router you're using? And, this might be a stupid question but, does the `Link` work when it's outside the Tooltip?

For the customisation of the position, it's not currently possible, I'd have to change the code to allow it.

**Comment by mnazim** [comment]
`react-router` is @ `1.0.3`

**Comment by romainberger** [comment]
I've [fixed the issue](https://github.com/romainberger/react-portal-tooltip/commit/31f32d93d0d367831946171558da6ed6f746e6b4), the patch is available on version 1.1.1

Thanks for reporting this!

**Comment by mnazim** [comment]
Hi, I asked this sometime back,

>> Another question I have is, that how do I add css for customising the position of popover. I want to move it up 10px from where it's displayed right now.

> For the customisation of the position, it's not currently possible, I'd have to change the code to allow it.

Hello, is there any plan of adding this?
Thanks

**Comment by romainberger** [comment]
Hi, Unfortunately I don't plan on implementing this for now due to lack of time. I think it would be doable by adding some props and summing the values after the position is calculated.
