### ISSUE TITLE
An invalid or illegal string was specified

### ISSUE THREAD

**Issue by nesbtesh** [romainberger/react-portal-tooltip#22]
Hi, react It doesn't allow me to dynamically set the id and parent of the object.

`var rowID = id + auditeeAssignee,`
			`rowHas = "#" + rowID;`

`<a href={link} id={rowID} className="malibu-text click" onMouseEnter={this.showTooltip.bind(this)} onMouseLeave={this.hideTooltip.bind(this)}>`
		`<span>{id}</span>`
`</a>`
`<ToolTip active={true} position="top" arrow="center" parent={rowHas}>`
   ` <div>`
	  `<p>This is the content of the tooltip</p>`
     `</div>`
`</ToolTip>`
`

**Comment by romainberger** [comment]
Hi, So you have an error? What's the result of `rowHas`?

**Comment by nesbtesh** [comment]
It has the id of the row and the #

**Comment by romainberger** [comment]
Yes but what do you mean by "doesn't allow me to dynamically set the id"? Do you have an error and a stack trace?

**Comment by nesbtesh** [comment]
I need to show a tooltip whenever I hover over a row in a data table. So what I need is to set the parent of the tooltip dynamically. 

This is the error I get whenever the table renders 
"SyntaxError: An invalid or illegal string was specified"

**Comment by nesbtesh** [comment]
The issue is that the plugin doesn't let you add the parent dynamically.
