### ISSUE TITLE
Multiple Tooltips/Groups Feature

### ISSUE THREAD

**Issue by RanjithNair** [romainberger/react-portal-tooltip#24]
When i am trying to display multiple tooltips for my error validation on a form, it just displays the last one ignoring all the previous Tooltip components. I could see that the active prop on all of them is set to "True" as well. Is this a known issue or am i missing something?

I guess this has to be done via "groups" prop. I tried to access the below link to know more about its usage, but this doesnt seem to work. 
http://romainberger.github.io/react-portal-tooltip/#/groups?_k=7znvtw

Can you explain on its usage to display multiple tooltips at the  same time?

**Comment by romainberger** [comment]
Hi, it has to be done with the group prop indeed. The link works for me, what's not working on your side?

Basically you can have only one tooltip displayed at a time per group. So if you want all tooltip to be independent you'll have to set a different group for each one.

**Comment by RanjithNair** [comment]
Thanks @romainberger ! Thats exactly what i was looking for. 
In that link, the functionality of tooltips doesnt seem to work.
