### ISSUE TITLE
Hide on click outside the tooltip

### ISSUE THREAD

**Issue by oyeanuj** [romainberger/react-portal-tooltip#29]
Hi @romainberger! I am trying to use tooltips to show form errors but I need to hide the tooltip if the user clicks anywhere outside the tooltip. I'm wondering if I can do that with `react-portal-tooltip`?

Thank you for open sourcing the library!

**Comment by ferpintado** [comment]
+1 looking for this feature as well.

**Comment by romainberger** [comment]
Hi,

This is not something that can be included in this library. You'll need to catch the click outside the element than trigger an action or something to hide the tooltip.  Here is a quick example of what I'm talking about: http://codepen.io/anon/pen/egxjNm
