### ISSUE TITLE
How is this repo related to weflex/react-portal-tooltip ?

### ISSUE THREAD

**Issue by sompylasar** [romainberger/react-portal-tooltip#34]
https://github.com/weflex/react-portal-tooltip has got an additional `transition` prop, but has a lower version (1.0.1) and no stars (1 so far).

**Comment by romainberger** [comment]
Well even though it's not a fork the code is clearly based on mine, I don't know anything else about it.

**Comment by sompylasar** [comment]
I see, thanks!
