### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by adamtal3** [romainberger/react-portal-tooltip#37]
Just started using this library and it's really helpful. Great job.

Seeing it has 4k npm downloads in the last month but no commits / issues responses for about 2 months I'm a bit worried.
@romainberger - are you there? Can we use `react-portale-tooltip` with no worry?

Thanks for this project. And again, really helpful.

**Comment by romainberger** [comment]
Hi,
I haven't been active for a few month but I'm still there ;) If there is any blocking issue in the future I'll be handling them.

**Comment by adamtal3** [comment]
Good to know!
