### ISSUE TITLE
Using Tooltip for option select

### ISSUE THREAD

**Issue by wwaterman12** [romainberger/react-portal-tooltip#38]
Really like your tooltip! Having a slight issue I hope you can help with.

Using Tooltip for option select and toggling whether it's open or closed based on clicking. My issue is that after clicking an option within the Tooltip, the Tooltip won't close until the mouse is no longer hovering over the option menu. I'm pretty sure it's from this line in your source code:

`visibility: this.state.hover || this.props.active ? 'visible' : 'hidden',`

Is there a work around for this?

**Comment by Redmega** [comment]
Looks like #23 addresses this.
