### ISSUE TITLE
Not maintained frequently?

### ISSUE THREAD

**Issue by Redmega** [romainberger/react-portal-tooltip#41]
Hi @romainberger,

I love the component and am using it in a project but I need some changes from some open pull requests. I noticed you seem quite busy and was wondering if you might want someone added as a maintainer for this project? I would be happy to take up that mantle.

Apologies if this is intrusive or uncouth. I just want to see this library succeed and to use it to its fullest potential for myself and my projects.

**Comment by tanqhnguyen** [comment]
I am also happy to help maintain this since we are using it for our project and I really like the library

**Comment by romainberger** [comment]
Hi guys, sorry for the delay. Thanks for your interest in this project. I don't personally use this module anymore so I lost interest in maintaining it, so if you're are still up for this I can add you as maintainers. 
Let me know and I'll add you on the repo and on npm so you can update and publish it.

Thanks again!

**Comment by Redmega** [comment]
Definitely still interested!

**Comment by romainberger** [comment]
Cool, let's do this! 

I'll add you to the repo, and if you can give me your npm username so I can add you as contributor. Then I trust you to do good things!

Thanks a lot for doing this!

**Comment by Redmega** [comment]
@romainberger Sweet 👍  Should be the same as my github, [Redmega](https://www.npmjs.com/~redmega).

**Comment by tanqhnguyen** [comment]
I am still interested since we are using this package actively in our current project. I am happy to help maintain it :)

**Comment by romainberger** [comment]
@tanqhnguyen Sure! Let me know your npm username and I'll add you as well. Thanks for your interest!

**Comment by tanqhnguyen** [comment]
It's **tanqhnguyen**, it's my new npm account because I can't change the username of the old one :)

**Comment by romainberger** [comment]
Alright you guys are all set! Thanks again for doing this!
