### ISSUE TITLE
close tooltip with Javascript

### ISSUE THREAD

**Issue by suziesirena** [romainberger/react-portal-tooltip#46]
Hi,

is there a way to close the tooltip programmatically?

For example:
```
<ToolTip active={this.state.isTooltipActive} position="top" arrow="center" parent="#text">
    <button onClick='this.closeToolTip'>CLOSE</button>
</ToolTip>
```

**Comment by Gardezi1** [comment]
yeah there is just make isTootipActive to false and it will close

**Comment by Redmega** [comment]
Like @Gardezi1 said, in your code if you do `this.setState({ isTooltipActive: false })`, it will close the tooltip.
