### ISSUE TITLE
Clarify groups functionality

### ISSUE THREAD

**Issue by oyeanuj** [romainberger/react-portal-tooltip#5]
I was going through the documentation and example, but still didn't really grasp the group functionality? Could you please clarify that - how does it work, and when would it be useful to have?

Also, when we have multiple tooltips on a page (like in your examples), is there a way to just have one component and refresh its props than having multiple tooltip components?

**Comment by romainberger** [comment]
Hi,

Groups can be useful when you want multiple tooltips like in this example: http://romainberger.github.io/react-portal-tooltip/#/groups

when you jump from one group to another there are two tooltips and it's not one tooltip moving from top to bottom. 

For you second question, do you mean having a single `<Tooltip/>` component in your code? If that's what you mean I'm not sure this would be easier as it would require some events (or flux implementation) to pass the props to the tooltip. 
I actually like the idea but forcing people to have a data management for this is a bit harsh IMO.
