### ISSUE TITLE
componentWillUnmount is not a function

### ISSUE THREAD

**Issue by elihofni** [romainberger/react-portal-tooltip#52]
![image](https://user-images.githubusercontent.com/13167779/29472403-0b2e2f96-842a-11e7-8731-06f9e86ce10f.png)

**Comment by tanqhnguyen** [comment]
Hi, 

Can you provide more info? Such as
- React version
- react-portal-tooltip version

Thanks

**Comment by elihofni** [comment]
react: 15.4.2
react-portal-tooltip version: 0.14

I'm using a single page application. When I change routes the ToolTip crashes.

**Comment by Redmega** [comment]
@elihofni Is it possible to make a [Codesandbox](codesandbox.io) showing the issue? I'm not able to replicate on my local.

**Comment by elihofni** [comment]
https://codesandbox.io/s/542kny3r3p

**Comment by Redmega** [comment]
> Anyhow, I had to do a few wierd code to make the ToolTip suits to me, like, I wanted a content update inside it, so I had to hide-n-show it. (It would be cool to pass a prop for this)

Not understanding, can you explain? (Maybe even update the codesandbox? 😉)

> Other point, I wished the ToolTip to show on click and hide on click somewhere out of it, so I managed a WatchOutsideClick component. (Would be nice to pass a prop for this too)

Probably won't be done as per #29

**Comment by Redmega** [comment]
I'm closing this issue unless anything else comes up...

As far as the hide-n-show thing, please open a new issue for that if you want!

**Comment by elihofni** [comment]
Cool, I've forked this repo and fixed the 'bugs' I said. As soon as possible I return the changes as a PR if you want
