### ISSUE TITLE
Arrow not centered with position=top/bottom and arrow=left/right

### ISSUE THREAD

**Issue by ClemDelp** [romainberger/react-portal-tooltip#54]
Hello guys thanks for this great component! I found that the arrow size was not take in consideration to compute its position:

![image](https://user-images.githubusercontent.com/4126690/29709575-25a60598-898d-11e7-92d7-d6c871c64b9e.png)

It's almost invisible for big or medium element but if you want to use it around an icon you can see a slight offset.

I propose a solution [here](https://github.com/romainberger/react-portal-tooltip/pull/53)

By introducing the arrow size it's looks perfectly centered:

![image](https://user-images.githubusercontent.com/4126690/29709687-9e2879e2-898d-11e7-90d9-cd120b609263.png)

**Comment by tanqhnguyen** [comment]
Merged, thanks for the PR :)
