### ISSUE TITLE
Stateful tooltip?

### ISSUE THREAD

**Issue by tanqhnguyen** [romainberger/react-portal-tooltip#56]
I know that having stateless components is more desirable, but I find myself repeating the same pattern again and again when I want to use `react-portal-tooltip`

- Listen to `onMouseEnter`, `onMouseLeave` events
- Change `active` state accordingly
- Re-render tooltip

I am thinking that it could be better if we have a "stateful" version of `react-portal-tooltip`. For example

```
const button = (
  <button>Show tooltip</button>
)
<StatefulToolTip trigger={button} showOn="mouseEnter" hideOn="mouseLeave">
  Actual content of the tooltip
</StatefulToolTip>
```

Let me know if you think it's useful to have such component :)

**Comment by FerusAndBeyond** [comment]
Since noone is working on the issues, I'd suggest you to create one yourself and wrap it as a new component.

**Comment by romainberger** [comment]
Definitely a good idea, I'd suggest to keep it under another import, like `import StatefulTooltip from 'react-portal-tooltip/stateful'` or something, so the original version is kept.

**Comment by romainberger** [comment]
Done in `v2.3.0`
