### ISSUE TITLE
Arrow positioning

### ISSUE THREAD

**Issue by ClemDelp** [romainberger/react-portal-tooltip#62]
Hi guys thanks again for this component it's really useful. I found two little bugs on the arrow position when the tooltip go outside the screen:

- when position = bottom / top & arrow right
![image](https://user-images.githubusercontent.com/4126690/32660173-1bd77476-c622-11e7-9f2f-6317574c3e67.png)

- when position = bottom / top & arrow = center the position is not really center:
![image](https://user-images.githubusercontent.com/4126690/32660327-af4ec696-c622-11e7-9463-c6b46f02253d.png)

I propose a fix here: https://github.com/romainberger/react-portal-tooltip/pull/61

**Comment by Redmega** [comment]
Fixed as of `v2.1.1`
