### ISSUE TITLE
Insane CPU usage

### ISSUE THREAD

**Issue by d07RiV** [romainberger/react-portal-tooltip#65]
The demo page (http://romainberger.github.io/react-portal-tooltip/) is bringing my CPU usage up to 80% immediately.

![image](https://user-images.githubusercontent.com/3448203/33801661-142074e0-dd73-11e7-961b-b97903334979.png)

I think it's something to do with timers, but I couldn't profile it properly when my PC is freezing every few seconds.

Update: can't reproduce on another PC, will check again.

**Comment by Redmega** [comment]
What are the specs of that machine?

**Comment by Redmega** [comment]
Closing as stale
