### ISSUE TITLE
Not able use tooltip for multiple elements with same event in React

### ISSUE THREAD

**Issue by Uvii** [romainberger/react-portal-tooltip#69]
When I'm trying to utilize tooltip for multiple elements data is not updating with respect to the element, I can see the message from last element for all the elements. Kindly suggest me some solution for multiple tooltips.

```html
<div id="hoverMe" onMouseEnter={this.showTooltip} onMouseLeave={this.hideTooltip}>
                Hover me!!!
</div>          

<div id="leaveme" onMouseEnter={this.showTooltip} onMouseLeave={this.hideTooltip}>
          Hover mine!!!
</div>
```
here is render function
```js
import ToolTip from 'react-portal-tooltip';

showTooltip(e) {
    console.log(e, e.target, e.target.name, e.options);
    this.setState({isTooltipActive: true})
  }
  hideTooltip(e) {
    this.setState({isTooltipActive: false})
  }

 this.showTooltip = this.showTooltip.bind(this);
 this.hideTooltip = this.hideTooltip.bind(this);

this.state = {
    isTooltipActive : false
}
```
And one more method which I had tried is that passing message as a parameter as follows

```js
toolTip(e, value) {
    console.log(e, value);
    // this.setState({isTooltipActive: true});
    return (<ToolTip active={this.state.isTooltipActive} position="top" arrow="center" 
        parent="#hoverMe">
        <div>
            <p>{value}</p>
        </div>
    </ToolTip>);
  }

 <div id="hoverMe" onMouseEnter={(e) => this.toolTip(e, "hrloo mcsdo!!1")} onMouseLeave={this.hideTooltip}>
                Hover me!!!
            </div>
```
But, unfortunately It's not working hope It have some mistakes. Suggest me some workable way in to this

**Comment by Redmega** [comment]
The issue with doing it this way is that you are using the same state to control two tooltips and expecting it to work. Try setting two different states ( `tooltip1Active`, `tooltip2Active`) , or try moving each `<div>` that needs a tooltip into its own component with its own tooltip state. Personally I would go with the latter.

**Comment by Redmega** [comment]
Closing as stale
