### ISSUE TITLE
Warning: Failed prop type: The prop `parent` is marked as required in `ToolTip`, but its value is `undefined`.

### ISSUE THREAD

**Issue by pppgod** [romainberger/react-portal-tooltip#71]
When I was set the 'parent' prop as ref,  I could see this warning

> Warning: Failed prop type: The prop `parent` is marked as required in `ToolTip`, but its value is `undefined`.

but 'Tooltip' is good working!

what happen?

**Comment by pppgod** [comment]
I think is rendering  time issue in React. 
I resolve this problem. setting a initial value to this.{ref}.

**Comment by vitalybe** [comment]
It happens because React only sets ref after a component mounted, but the tooltip checks it from the beginning (which is a bug imo).

Here is how I handle that:

`parent={this.ref || ""}`

**Comment by bradennapier** [comment]
lol
