### ISSUE TITLE
Ability to tweak disappear animation speed

### ISSUE THREAD

**Issue by ndelangen** [romainberger/react-portal-tooltip#78]
I'd like the appear & disappear animation to be quite a bit faster.

How can I achieve this?

I'd want something like 160ms.

**Comment by romainberger** [comment]
There is a `tooltipTimeout` prop to control that: https://github.com/romainberger/react-portal-tooltip#props

**Comment by ndelangen** [comment]
Yes, thank for the help @romainberger, I've read the docs.

Seems like that prop is only for removing or lengthening the delay when removing the tooltip

I've set it to 0, but the animation is still taking half a second.
