### ISSUE TITLE
[TS] Add typings

### ISSUE THREAD

**Issue by PlayMa256** [romainberger/react-portal-tooltip#79]
Hello, i would like to add typescript support (typings) to this package. If a PR is created, would it be accepted?

**Comment by Redmega** [comment]
Absolutely!

**Comment by romainberger** [comment]
Hi, thank you for your interest and your proposition. 
Unfortunately I'll have to put a veto on that, I'm not a fan of typescript and the overhead it adds just for a small module like that. I like the idea of using typing for a more robust code, but I'd rather use flow than typescript.

**Comment by Redmega** [comment]
In that case, you can make a PR to DefinitelyTyped (https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) seeing that this package isn't originally written in typescript

**Comment by PlayMa256** [comment]
ok!
