### ISSUE TITLE
[BUG] Uncaught Error: Maximum update depth exceeded... - In the <Card> component, using StatefulTooltip

### ISSUE THREAD

**Issue by JZBo** [romainberger/react-portal-tooltip#84]
Hello everyone,

I'd like to report a very weird issue with React-Portal-Tooltip (version 2.4.2 and 2.3.0), when using the StatefulToolTip component.

I've noticed, only in **SOME** of the tooltips of a project, that the console printed an error stack like this one, even though said tooltips appeared to be working normally:

> Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (react-dom.development.js:55)
    at scheduleWork (react-dom.development.js:18734)
    at Object.enqueueSetState (react-dom.development.js:12457)
    at Card.renderer../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:375)
    at Card.updateSize (index.js:342)
    at Card.componentDidUpdate (index.js:333)
    at commitLifeCycles (react-dom.development.js:16242)
    at commitAllLifeCycles (react-dom.development.js:17592)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)

> The above error occurred in the <Card> component:
    in Card

Further investigation allowed me to notice that this error stack appeared if and when I moved the cursor over the tooltip content, and then moved it outside the boundaries of the displayed Tooltip Content.
Once again, this happened in **SOME** of the tooltips.
The tooltip content is a simple unstyled div with text, and no options are used except the positioning of the tooltip.

At the beginning I thought it only happened when the Tooltip Parent was a <span> instead of a <div>, but unfortunately I found out that this is not the case. I haven't been able to find a common feature that would allow me to predict or discerne between the elements having this issue, and the ones that didn't.
I can also report that I'm using react v 16.7.0.

It's not a completely feature breaking bug, but it might be worth investigating, because something is definitely not going on as intended.

**Comment by valadas** [comment]
I have isolated the issue to very specific lenghts of the tooltip content, adding or removing 1 letter fixes it, I guess during the transition to show it, it must pass under the cursor and quickly starts switching between visible and hidden it rapid successions in an endless manner.

**Comment by JZBo** [comment]
> I have isolated the issue to very specific lenghts of the tooltip content, adding or removing 1 letter fixes it, I guess during the transition to show it, it must pass under the cursor and quickly starts switching between visible and hidden it rapid successions in an endless manner.

> Actually it is the parent element length not the tooltip content.

Do you have any temporary workaround for this? It's not breaking, but sure as hell is troublesome and annoying.

Which one is the safe length for the parent element? Because, for instance, I'm having the same issue in one out of two tooltips, both of those with the same 'empty' parent element (just a svg icon, albeit a different one), but one crashes and the other doesn't.

**Comment by valadas** [comment]
And I have the issue on only some of them, also an svg icon. All of them have the same icon but the issue only happen in some.

We have something similar to:
```html
<div className="form-group">
    <label style={{float:"left"}}>Field Name</label>
    <div id="tooltipId" className="icon" style={{float:"left"}}>
        <InfoIcon  />
    </div>
</div>
<ReactPortalTooltip parent={"#tooltipId"} >
    <div dangerouslySetInnerHTML={{__html: message}} />
</ReactPortalTooltip>
```

I have omitted some props and inlined styles for clarity.
We have solved the non working ones by adding width: xx% to the div#tooltipId, but only some specific values work, changing the percentage makes it work/not-work. Very strange indeed.

**Comment by valadas** [comment]
Found a way to make a storybook story that reproduces the issue if it helps:

## Steps to reproduce
1. run git clone https://github.com/valadas/Dnn.React.Common/tree/label-tooltip-stories
2. run yarn install
3. run yarn storybook
4. Go to the story Label -> Reproduces issue
5. Notice error in console

## Additional context
- The other stories with a tooltip are very similar but do not encounter the issue
- That repository is a collection of components only, so it is not an app on itself but is reused in a large app, so running webpack on it just does not generate a usable app, hence the storybook.
- Lower in the storybook are a couple of usages of the Tooltip alone, the Label component renders a label and an optional tooltip.

**Comment by valadas** [comment]
After some more investigation, it varies from user to user on which ones the issue happens and does not. Probably dependent on os/browser/resolution combination or something...

**Comment by JZBo** [comment]
Can confirm that the issue is solved, thank you very much.

**Comment by valadas** [comment]
In our case it only partlially fixed it we still have issues but it changed on which labels, very odd.

**Comment by Redmega** [comment]
🤔 Very interesting. Would you like me to re-open the issue @valadas?

I don't currently have the time to investigate with you but I'd be happy to be here as a sounding board.
