### ISSUE TITLE
active props doest not seems to work with StatefulToolTip

### ISSUE THREAD

**Issue by jinmayamashita** [romainberger/react-portal-tooltip#88]
Hi, I'm using react-portal-tooltip to be shown on hover as well in StatefulTooltip.
But, When I added `active` props to react-portal-tooltip and it seems not working.  

Do you know how I can make the tooltip active instantly in StatefulToolTip ?

[Here is my Sandbox](https://codesandbox.io/s/8yvny87ym8)

**Comment by Redmega** [comment]
Any reason why you can't use Tooltip? StatefulTooltip keeps track of active and hover internally.

**Comment by Redmega** [comment]
If you want to control `active` you need to use `Tooltip`.

**Comment by jinmayamashita** [comment]
Can I use Tooltip in Stateless functional component with `refs`? :eyes:

**Comment by jinmayamashita** [comment]
But thanks for your comment!
I'll use `Tooltip` with my component! 👍

**Comment by Redmega** [comment]
No, refs require the `class` and _something_ will need to control `active` unless you want it always showing.

**Comment by jinmayamashita** [comment]
Yes, It's exactly as you said. maybe I change my component to `class`. thanks a lot!
